"""add_warmup_cooldown_to_workout_templates

Revision ID: 83dd52a38bdc
Revises: 0d4df2102a99
Create Date: 2026-07-08 08:41:37.514688+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83dd52a38bdc'
down_revision: Union[str, None] = '0d4df2102a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_templates', sa.Column('warmup_seconds', sa.Integer(), nullable=True))
    op.add_column('workout_templates', sa.Column('cooldown_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_templates', 'cooldown_seconds')
    op.drop_column('workout_templates', 'warmup_seconds')
    # ### end Alembic commands ###
