"""add indexes on hot query columns (NER-299)

Revision ID: 14210fb828f7
Revises: a3f1c07d5b62
Create Date: 2026-08-11 19:08:26.299753+00:00
"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '14210fb828f7'
down_revision: Union[str, None] = 'a3f1c07d5b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_boxing_entries_date'), 'boxing_entries', ['date'], unique=False)
    op.create_index(op.f('ix_cycling_entries_date'), 'cycling_entries', ['date'], unique=False)
    op.create_index(op.f('ix_run_entries_date'), 'run_entries', ['date'], unique=False)
    op.create_index(op.f('ix_session_exercises_session_id'), 'session_exercises', ['session_id'], unique=False)
    op.create_index(op.f('ix_weight_entries_date'), 'weight_entries', ['date'], unique=False)
    op.create_index(op.f('ix_workout_sessions_started_at'), 'workout_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_workout_sessions_template_name'), 'workout_sessions', ['template_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_sessions_template_name'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_started_at'), table_name='workout_sessions')
    op.drop_index(op.f('ix_weight_entries_date'), table_name='weight_entries')
    op.drop_index(op.f('ix_session_exercises_session_id'), table_name='session_exercises')
    op.drop_index(op.f('ix_run_entries_date'), table_name='run_entries')
    op.drop_index(op.f('ix_cycling_entries_date'), table_name='cycling_entries')
    op.drop_index(op.f('ix_boxing_entries_date'), table_name='boxing_entries')
    # ### end Alembic commands ###
