// Test stub for the VitePWA virtual module `virtual:pwa-register/react`.
// The real module is only generated by the VitePWA plugin during dev/build;
// vitest doesn't run that plugin, so vitest.config.ts aliases the virtual id
// to this stub. Tests that need to exercise the SW update flow mock this
// module with vi.mock (see useServiceWorkerUpdate.test.ts).
export interface RegisterSWOptions {
  onOfflineReady?: () => void;
  onNeedRefresh?: () => void;
}

export interface RegisterSWResult {
  needRefresh: [boolean];
  offlineReady: [boolean];
  updateServiceWorker: (reloadPage?: boolean) => void;
}

export function useRegisterSW(): RegisterSWResult {
  return {
    needRefresh: [false],
    offlineReady: [false],
    updateServiceWorker: () => {},
  };
}
